### ISSUE TITLE
Option to drop decimals if 0

### ISSUE THREAD

**Issue by TomWhitson** [akaunting/laravel-money#43]
Would it be possible to add an option to drop decimal if based on format it gives 0.

I suppose it would work best as an option when parsing the data in where you check for a float etc

**Comment by mlambley** [comment]
Hi @TomWhitson The referenced PR will allow you to use:
```php
Money::USD(100, true)->formatWithoutZeroes(); //$100
Money::USD(100.5, true)->formatWithoutZeroes(); //$100.50
```

Will that work for you?
