### ISSUE TITLE
Default currency

### ISSUE THREAD

**Issue by atorscho** [akaunting/laravel-money#47]
Hello,

Is there a possibility to set a default currency? So that I can use EUR without having to specify it in each `money` call.

Thank you.

**Comment by alliuqemal** [comment]
if PR #48 is merged, you'll be able to define your default currency in the env file 

`
DEFAULT_CURRENCY=EUR
`

**Comment by EnriqueRBT** [comment]
¿Not merged yet?

**Comment by zarulizham** [comment]
Default currency will fallback to **USD** after `php artisan optimize`. env() should not be called directly outside from config files.
