### ISSUE TITLE
jsonSerialize error

### ISSUE THREAD

**Issue by dhi2** [akaunting/laravel-money#58]
PHP: 8.1
Laravel: 8

`
Got error 'PHP message: PHP Deprecated:  Return type of Akaunting\\Money\\Money::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/akaunting/money/src/Money.php on line 869',
`

Referencing this line: https://github.com/akaunting/laravel-money/blob/c48cb9744c2083be62922bb1dc09d014689e22e1/src/Money.php#L869

**Comment by Simoneu01** [comment]
Same problem on Currency.php:

`Return type of Akaunting\Money\Currency::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/akaunting/laravel-money/src/Currency.php on line 483  `

Referencing this line:
https://github.com/akaunting/laravel-money/blob/8f85eaf4e6a560bed0951c3fa27ad668a9a15b38/src/Currency.php#L483

**Comment by denisdulici** [comment]
Fixed in 2.0 version.
