### ISSUE TITLE
Remove decimal places in Blade view

### ISSUE THREAD

**Issue by Darrrren** [akaunting/laravel-money#63]
Is it possible to display a value without any decimal places from within the Blade view?  For example to display $500.00 as $500
```php
@money(500,'USD',true) 
```
always returns $500.00 but I need $500

**Comment by denisdulici** [comment]
You can achieve that by setting the `precision` of that currency to 0 in the `money` config file.

**Comment by Darrrren** [comment]
Hi Denis, I don't want to change the precision in the config file, that will change the precision for every object in this currency across the whole site which is wrong.  I want to display the variable in a summary field in a blade view but without the decimal places, for example in a financial forecast like this:

|  | 2021 | 2022 | 
| --- | --- | --- |
| Sales Revenue | $250.50 | $300.75 |
| Cash Sales | $100.10 | $200.60 |
| **TOTAL INCOME** | **$351** | **$501** |

You can see here I want to display USD with 2 decimals in the Revenue and Sales rows but without the decimals in the Total Income field...

Does this functionality exist?

**Comment by denisdulici** [comment]
Unfortunately, that's not possible.
