### ISSUE TITLE
Missing variable.

### ISSUE THREAD

**Issue by RonJeremyR6** [akaunting/laravel-money#73]
I miss a variable where you can set the comma or dott before it goes into the money function.
For example:
When I retrieve a float number from my database, it consists of a dot, like: 40.5
When I use EUR:
'EUR' => [
        'name'                => 'Euro',
        'decimal_mark'        => ',',
        'thousands_separator' => '.',
    ],
I get the result: 405,00 EUR.
Now I don't want to replace the dots to commas first from my database values.
If there was a variable like: 'decimal_mark_db' => '.' and the money function handles it, that would be great.

**Comment by denisdulici** [comment]
Unfortunately, that's not possible.
