### ISSUE TITLE
Caching configs stops env() funtion working

### ISSUE THREAD

**Issue by ashleyhood** [akaunting/laravel-money#75]
When configs are cached then `env()` method will always return the default option. 

https://github.com/akaunting/laravel-money/blob/cbc66d1dc457c169f6081e0ae6c661b499dad301/src/helpers.php#L11

I suggest moving the `env('DEFAULT_CURRENCY', 'USD')` into the config.

```php
<?php

return [
    'default_currency' => env('DEFAULT_CURRENCY', 'USD'),

    ...
];

```

**Comment by ashleyhood** [comment]
I'm willing to do a pull request if this is something that is wanted.

**Comment by ashleyhood** [comment]
I have just seen #72 pull request. Is there any reason this has not been merged?

**Comment by leeuweriq** [comment]
Can this #72 please be merged? Referring to the env directly from code and not through a config is really bad and makes config caching impossible.

**Comment by dpslwk** [comment]
This is still a problem! even though #55 was close and #56 was not accepted

**Comment by erenergul** [comment]
Same issue. I tried to clean config but still USD.  env function doesn't work. so I added currency="EUR" every each blade. That was really bad experience.

**Comment by Superanton** [comment]
@money-helper-function doesn't work right now with a default currency set other than USD. Laravel-Money's blade-template references DEFAULT_CURRENCY but it's not specified in the config file. #72 should be merged!
