### ISSUE TITLE
Not working as expected (details in the description)

### ISSUE THREAD

**Issue by maxacarvalho** [akaunting/laravel-money#85]
Hi,

I'm using the package to work with amounts in Brazil, so thousand separator is `.` and decimals separator is `,`.

I'm facing an issue with some values, for example, `1000` (one thousand).

Here's an example, I did a comparison with the `Brick\Money` lib:

```php
$money = new \Akaunting\Money\Money('1000', new \Akaunting\Money\Currency('BRL'));
$bmoney = \Brick\Money\Money::of('1000', 'BRL');

return [
  $money->getAmount(),
  $bmoney->getMinorAmount()->toInt(),
];
```

Outputs:
- `1000` **wrong**
- `100000` **right**

**Comment by miomech** [comment]
I think you need to do the following:

- Pass the third parameter (bool) to "convert" as it parses
- **Convert** means: "take the input and multiply it by the currency's subunit". 
- This is defined in your [money.php config file](https://github.com/akaunting/laravel-money/blob/master/config/money.php) currency sub unit defined in the config.
```PHP 
    'BRL' => [
        'name' => 'Brazilian Real',
        'code' => 986,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'R$',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
    ],
```
- We convert when taking input from the user so we can store all our currency values as raw non float values. 

In the example below notice that usage1 and usage 2 have the boolean **convert** enabled. So we pass it 1000. It takes this **Value** and multiplies it by the currency's subunit. In this case the subunit for Brazilian currency is "100", so 1000 * 1000 = 100000.

We now have a variable "$money" which has a **"amount" of 100000**, and a **"value" of "1000.0"**
When we call the format function it will take the info from your money.php config file and do its magic :)

```PHP
use \Akaunting\Money\Money;
use \Akaunting\Money\Currency;

// Usage 1:
$money = new Money('1000', new Currency('BRL'), true); // Stores "amount" of: 100000

// Usage 2: (Cleaner)
$money = Money::BRL(1000, true); // Stores "amount" of: 100000

echo $money->getValue(), // Outputs: 1000.0
echo $money->format(), // Outputs: "R$1.000,00"
```
I haven't used brick money package so I can't help you there. I also had a bit of trouble figuring out this package but I hope this helps! 

Sorry if there are any mistakes. Take care my friend!

**Comment by andrewdwallo** [comment]
Currency conversion only seems to work correctly when using double... why is this? Isn't using double type a bad idea and can lead to inaccuracies? I tried to use decimal type in my database and currency conversions are not accurate.

**Comment by miomech** [comment]
@andrewdwallo 
Not sure, I've been using this package in my projects without issue. 

Can you post a snippet of your code you're having trouble with?
I can look at it and try to help you out.

**Comment by andrewdwallo** [comment]
@miomech If I use, for example, this as the balance for a currency in my database:
```
$table->decimal('opening_balance', 15, 4)->default(0.0000);
```
In USD, if I have $0.40, (which would show as 0.4000 in the database) and convert this to EUR it will show 4.000,00 as the format (even though it still shows 0.4000 as the value in the database), when in actuality the format for the value in EUR would be 0,40

**Comment by miomech** [comment]
Understandable. 

What I do is store the money as JSON. 
``` PHP
$table->json('amount');
```

Then in the model I use the 'MoneyCast' that comes with the Laravel-Money package [See here](https://github.com/akaunting/laravel-money/tree/master/src/Casts)

```PHP
use Akaunting\Money\Casts\MoneyCast;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $casts = [
        'price' => MoneyCast::class,
    ];
```

With that set up I can just pass in a 'Money' object when creating a model (in this case a product)
The model will automatically be serialized into a json object and stored in the database 
```PHP

Product::create([
    // The cast will serialize this to json and store it in the database
    // In this case I am using a string of '.04', the "true" arguement will convert this to 40
    'amount' => Money::EUR('35.72', true), 
]);
```

When I call the 'price' attribute on a model it will automatically return back a 'Money' object that it rebuilt from the stored json data.

So if I want to use it I simply:
```PHP

$product = Product::find(1); // Assuming the created product had an ID of 1
$product->price // The cast will automatically take the database json data and hand me a money object.

$product->getAmount() // Will give you 357200
$product->getValue() // will give you 35.72
$product->format() // Will give you €35,72
```

I can't run the code at the moment so I just wrote that above off the top off my head, I'll come back later and make sure I didn't add any bugs. With that said. I hope the general idea comes across. Hope that helps!

I think It may be helpful to update the documentation on this package page, Maybe I'll update it and submit a PR.

**Comment by andrewdwallo** [comment]
@miomech Okay thanks. I will try this soon and see how it goes. I use Filament and we currently use this to format values:
https://filamentphp.com/docs/2.x/tables/columns/text#currency-formatting

Something like this as an example:
```
TextColumn::make('price')->money('EUR', true)
```

After having discussed this with other users who use Filament who have had issues when formatting currency amounts, I am guessing this applies to most users who use anything other than `double`, and I would guess that would be a lot of users. That would be great if a PR was made for formatting `decimal` type but I just thought I should let you know. Thank you for your time and help and I will get back to you shortly!

**Comment by miomech** [comment]
@andrewdwallo No worries, I use Filament as well and have been able to use this without problems. Just spent that last two weeks getting this thing to work and its working great! If you need any extra info let me know.

**Comment by chrisidakwo** [comment]
> @miomech If I use, for example, this as the balance for a currency in my database:
> 
> ```
> $table->decimal('opening_balance', 15, 4)->default(0.0000);
> ```
> 
> In USD, if I have $0.40, (which would show as 0.4000 in the database) and convert this to EUR it will show €4.000,00 as the format (even though it still shows 0.4000 as the value in the database), when in actuality the format for the value in EUR would be €0,40.
> 
> When changing the format in the database as this:
> 
> ```
> $table->double('opening_balance', 15, 4)->default(0.0000);
> ```
> 
> Everything works correctly here, but using double is not the best option when dealing with currencies and when precise amounts matter... especially over time.

@andrewdwallo I'm not sure why you would use `double` to save a currency value, but I've found that it's always best to save money in the smallest unit - hence an int in 99% of the case (or in more precise details as @miomech highlighted using JSON  - although I haven't done that before).

The smallest unit representing 1 dollar is 100 cents, so why not just save `$0.40` as `40` in your database, so that whatever library you use now or later or whatever programming language you switch to, it's always easy to convert without losing a cent or two in the process? Data migration also becomes easier between database engines. There are lots of advantages to that.

On the application level also, we work directly with the smallest units and only format when displaying to users. From experience,  it's a safer way to work with money values.

I have cases where I. worked on apps handling large currency values like `$451,892,943.12`, but because it's all persisted to DB as the cent value `45189294312`, even if we switch the backed to a new language, we do not necessarily need to check the language can properly handle floats or decimals or doubles as we expect. The only time we deal with the actual dollar value is on the frontend, when we have to display values to the user.

Every other operation, including conversions in code, and persisting to the DB should preferably be done on the smallest unit of the currency.

**Comment by andrewdwallo** [comment]
@chrisidakwo I wasn't sure why I would save it as a double as well but considering akaunting uses it to store their currencies, it works pretty well. I originally wanted to store it as a decimal but was unsuccessful in converting currencies, even though I think storing in decimal type should be supported. Decimal is supported in almost all languages so I would not be worried about that even though I won't be switching programming languages (considering this is a PHP package). Storing values as an integer, in my opinion, causes too much complexity. It complicates the business logic of the application and introduces error-prone value conversions between units, micro-units and normal currency amounts that are presented to a user or external systems.

Quote from somewhere online: Say you have a savings account with an interest rate of 0.125% and any interest has to be converted into another currency for taxation purposes at a rate of 0.88619. Working around these sorts of problems with integers is just not worth the trouble.

**Comment by andrewdwallo** [comment]
@miomech What's the largest value you can hold accurately with json? I would guess not as much as a system would be able to handle... I'm also learning that this will not go well for when you need to use fractional calculations, etc... I don't think storing as a json is practical.

**Comment by miomech** [comment]
I just ran a test, the largest number I can hold in json (safely) before I get overflow errors is:<br>

- `10,000,000,000,000,000` (ten quadrillion)<br>
- or *Nine quadrillion nine hundred ninety-nine trillion nine hundred ninety-nine billion nine hundred ninety-nine million nine hundred ninety-nine thousand nine hundred ninety-nine* (plus 1)

For my purposes I'll never be working with numbers that large. So I'm good to go.

Here is the code I used to test this out:
```PHP
use Akaunting\Money\Money;

$x = Money::USD('$10,000,000,000,000,000',true);

$x->getAmount(); // 1000000000000000000
$x->getValue(); // 1.0E+16
$x->format(); // "$10,000,000,000,000,000.00"
```

Saving this object to the database will save this:
```JSON
{"amount": 1000000000000000000, "currency": "USD"}
```

And this is what it looks like as a "Money" object
```PHP
Akaunting\Money\Money {#4135
  #amount: 1000000000000000000
  #currency: Akaunting\Money\Currency {#4134
    #currency: "USD"
    #name: "US Dollar"
    #code: 840
    #rate: 1.0
    #precision: 2
    #subunit: 100
    #symbol: "$"
    #symbolFirst: true
    #decimalMark: "."
    #thousandsSeparator: ","
  }
  #mutable: false
}
```

@andrewdwallo as @chrisidakwo pointed out you can also store everything as an int within the database. Thats is a pefectly viable option as well so long as you remember to always do your conversions properly in the code. For me this works for others it may not.

Take care!
